CREATE TABLE IF NOT EXISTS monthly_salary (
  id INT NOT NULL AUTO_INCREMENT,
  date DATE NOT NULL,
  year VARCHAR(4) NOT NULL,
  month VARCHAR(2) NOT NULL,
  description TEXT,
  total_employees INT DEFAULT 0,
  total_salary DECIMAL(12,2) DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS employee_salary (
  id INT NOT NULL AUTO_INCREMENT,
  salary_id INT NOT NULL,
  employee_id INT NOT NULL,
  salary DECIMAL(10,2) DEFAULT 0.00,
  bonus_ot DECIMAL(10,2) DEFAULT 0.00,
  absent_fine DECIMAL(10,2) DEFAULT 0.00,
  deduction DECIMAL(10,2) DEFAULT 0.00,
  payment DECIMAL(10,2) DEFAULT 0.00,
  note TEXT,
  signature VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (salary_id) REFERENCES monthly_salary(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;